const mongoose=require('mongoose')

const orderedSchema=new mongoose.Schema({
   shippingInfo:{
    address:{
        type:String,
        required:true
    },
    country:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    phoneNo:{
        type:Number,
        required:true
    },
    postalCode:{
        type:String,
        required:true
    }
   },
   user:{
    type:mongoose.SchemaTypes.ObjectId,
    required:true,
    ref:'user'
   },
   orderItems:[{
    name:{
        type:String,
        required:true
    },
    quantity:{
        type:Number,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    product:{
        type:mongoose.SchemaTypes.ObjectId,
        required:true,
        ref:'product'
    }
   }],
   itemsPrice:{
    type:Number,
    required:true,
    default:0.0
},
taxPrice:{
    type:Number,
    required:true,
    default:0.0
},
deliveryCharge:{
    type:Number,
    required:true,
    default:0.0
},
totalPrice:{
    type:Number,
    required:true,
    default:0.0
},
paymentInfo:{
    id:{
        type:String
    },
    status:{
        type:String
    }
  },
paidAt:{
    type:Date
},
deliveredAt:{
    type:Date
},
orderStatus:{
    type:String,
    required:true,
    default:"processing"
},
createdAt:{
    type:Date,
    default:Date.now
}
})


let ordering=mongoose.model('ordering',orderedSchema)
module.exports=ordering
